name: Add to Storage Explorer Project

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign-project:
    name: Assign to projects
    runs-on: ubuntu-latest
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.1
        name: Assign to Storage Explorer project
        with:
          project: 'https://github.com/microsoft/projects/140'
          column_name: 'Untriaged'
